# Generated by Django 3.2.8 on 2021-11-05 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211105_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
