# Generated by Django 3.2.8 on 2021-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
