# Generated by Django 3.2.8 on 2021-11-05 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
