# Generated by Django 3.2.8 on 2021-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
